$("#fav").click(function(){
    $(this).find("i").removeClass("bx-heart").addClass("bxs-heart");
});
$("#fav1").click(function(){
    $(this).find("i").removeClass("bx-heart").addClass("bxs-heart");
});$("#fav2").click(function(){
    $(this).find("i").removeClass("bx-heart").addClass("bxs-heart");
});
;$("#fav3").click(function(){
    $(this).find("i").removeClass("bx-heart").addClass("bxs-heart");
});
